### ISSUE TITLE
Could you please share the dataset?

### ISSUE THREAD

**Issue by xray1111** [Leavingseason/OpenLearning4DeepRecsys#2]
I could not find the dataset used for training and testing in DeepFM, such as 'data/part01.svmlight_balanced.csv' and 'data/part02.svmlight.csv'. Could you please tell me where I can find them? Thanks!

**Comment by Leavingseason** [comment]
files with name part01.XXX  are commented and are used for our debug purpose. Please unzip the S1_4_and_S5.zip and you will find the data files. 
If you failed to run the code, please delete all the .pkl files and run the code again.

**Comment by xray1111** [comment]
Got it! But if I want to test deepfm with the movielens dataset, do I have to make some changes to the code?

**Comment by Leavingseason** [comment]
You need to make some minor modifications such as change the field number and feature number. 
Then prepare the data in the same format as S1_4.txt.
